# Generated by Django 4.0.3 on 2022-03-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed index', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiker', models.CharField(max_length=6, null=True, unique=True)),
                ('company', models.CharField(max_length=255, null=True, unique=True)),
                ('sector', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=10, max_digits=13)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.marketindexes')),
                ('tiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.shares')),
            ],
        ),
    ]
