# Generated by Django 4.0.3 on 2022-03-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_rename_indexcomposition_etf_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etf_structure',
            old_name='tiker',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='tiker',
            new_name='ticker',
        ),
    ]
