# Generated by Django 4.0.3 on 2022-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_rename_tiker_etf_structure_ticker_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETFs',
            new_name='ETF',
        ),
        migrations.RenameModel(
            old_name='ETF_Structure',
            new_name='ETFStructure',
        ),
    ]
