# Generated by Django 4.0.3 on 2022-03-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_rename_etfs_etf_rename_etf_structure_etfstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfstructure',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
