# Generated by Django 4.0.3 on 2022-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_etfstructure_dt_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
