# Generated by Django 4.0.3 on 2022-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_shares_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfstructure',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
