# Generated by Django 4.0.3 on 2022-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_etfstructure_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='share_display_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
