# Generated by Django 4.0.3 on 2022-03-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_alter_shares_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shares',
            old_name='sector',
            new_name='index_sector',
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='company',
            new_name='index_short_name',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='share_display_name',
        ),
        migrations.AddField(
            model_name='shares',
            name='market_currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='market_day_high',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='market_day_low',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='market_fiftyTwoWeekHigh',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='market_fiftyTwoWeekLow',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('BusinessSummary', models.TextField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.shares')),
            ],
        ),
    ]
