# Generated by Django 4.0.3 on 2022-03-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_rename_sector_shares_index_sector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ticker',
            new_name='share',
        ),
        migrations.RenameField(
            model_name='etfstructure',
            old_name='ticker',
            new_name='share',
        ),
    ]
