# Generated by Django 4.0.3 on 2022-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_remove_company_share_shares_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etf',
            old_name='name',
            new_name='ticker',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='No longName', max_length=255, null=True),
        ),
    ]
