# Generated by Django 4.0.2 on 2022-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_remove_question_likes_answer_title_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question without mane', max_length=20),
        ),
    ]
