# Generated by Django 4.0.2 on 2022-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question without name', max_length=255),
        ),
    ]
