# Generated by Django 4.0.2 on 2022-03-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_myuser_alter_question_auhtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='auhtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.myuser'),
        ),
    ]
