# Generated by Django 4.0.2 on 2022-03-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_alter_question_auhtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='auhtor',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_rised', to='qa.myuser'),
        ),
    ]
