# Generated by Django 4.0.2 on 2022-03-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_remove_question_auhtor_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='qa.MyUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.myuser'),
        ),
    ]
