# Generated by Django 4.0.2 on 2022-03-07 14:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_remove_answer_title_remove_question_like_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('question_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
