# Generated by Django 4.0.2 on 2022-03-07 15:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_alter_question_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
