# Generated by Django 4.0.2 on 2022-03-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_alter_question_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
