# Generated by Django 4.0.2 on 2022-03-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
