# Generated by Django 4.0.2 on 2022-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_myuser_alter_session_user'),
        ('qa', '0020_alter_answer_author_alter_question_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='users.MyUser'),
        ),
    ]
