# Generated by Django 4.0.3 on 2022-04-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_userportfolio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostructure',
            old_name='amout',
            new_name='Shares',
        ),
        migrations.RenameField(
            model_name='portfoliostructure',
            old_name='share',
            new_name='Symbol',
        ),
        migrations.RemoveField(
            model_name='portfoliostructure',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.userportfolio'),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='TradeDate',
            field=models.DateField(null=True),
        ),
    ]
