# Generated by Django 4.0.3 on 2022-04-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_rename_name_etf_ticker_alter_company_company_name'),
        ('portfolios', '0003_rename_amout_portfoliostructure_shares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostructure',
            old_name='Shares',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='owner',
            new_name='Owner',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='IndexToFollow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.etf'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='Target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
