# Generated by Django 4.0.2 on 2022-06-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_myuser_alter_session_user'),
        ('portfolios', '0004_rename_shares_portfoliostructure_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuser'),
        ),
    ]
