# Generated by Django 4.0.2 on 2022-06-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_rename_name_etf_ticker_alter_company_company_name'),
        ('portfolios', '0005_alter_userportfolio_name_alter_userportfolio_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliostructure',
            unique_together={('Symbol', 'Portfolio')},
        ),
    ]
