# Generated by Django 4.0.2 on 2022-06-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_alter_portfoliostructure_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliostructure',
            unique_together=set(),
        ),
    ]
