# Generated by Django 4.0.2 on 2022-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_alter_portfoliostructure_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostructure',
            name='TargetQuantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostructure',
            name='TargetSum',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
